name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pobiera pełną historię Git zamiast shallow clone

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "piekarzewski@gmail.com"
          git config --global user.name "Paweł"
          git remote add space https://huggingface.co/spaces/Becer/pd2_pricing
          git push --force https://USERNAME:${HF_TOKEN}@huggingface.co/spaces/Becer/pd2_pricing main
